### ISSUE TITLE
Discord shows monitor mirrored

### ISSUE THREAD

**Issue by Tsubajashi** [TaPO4eg3D/discord-monitors-to-vc#7] opened 2019-08-24 14:10 UTC
Discord shows the camera mirrored.
![Screenshot_20190824_180513](https://user-images.githubusercontent.com/21346945/63638522-a1453f80-c689-11e9-87c9-9ac7311f75b1.png)

Manjaro KDE, 1080p + 768p Monitor

**Comment by TaPO4eg3D** [comment] 2019-08-24 14:26
Duplicate of https://github.com/TaPO4eg3D/discord-monitors-to-vc/issues/3

**Closed as completed** 2019-08-27 05:56 UTC
